# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c1561e519a863a23cbe293ff91ac9f0e56d5665e55ead46a8b8d202949c75523d0bd4ea45b3992bf2433b83511ee01e64c68e90410dc6379cebb1c019a812ac

test:
  secret_key_base: a2e19bec53fb6eb12479322ea492b5a45b138dcdb1338cb63085bc1ef3c15cba2ccb6ae2ea743c07fb8dbfe1e411f5c55bcde475c8e292a6524be816e2bb3e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
